services:
  frontend:
    image: daily-dev-client
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - VITE_BACKEND_URL=http://host.docker.internal:3000
    restart: always
