services:
  backend:
    image: daily-dev-backend
    container_name: backend-container
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    networks:
      - app-network

  frontend:
    image: daily-dev-client
    container_name: frontend-container
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
